FROM rust:1.55 AS build

WORKDIR /usr/src/client

COPY . .

RUN cargo build --release

FROM debian:buster-slim
COPY --from=build /usr/src/client/target/release/client-app /usr/local/bin/client-app

CMD ["client-app"]